import normalize from '../utils/helpers/dimen';
import {Colors, Fonts} from './Theme';
import {Margin, Padding} from './Spacing';
import {Dimensions, Platform, StatusBar, StyleSheet} from 'react-native';

export const mg = Margin(100);
export const pd = Padding(100);

export const {width, height} = Dimensions.get('screen');

const css = StyleSheet.create({
  ttn: {textTransform: 'none'},
  f1: {
    flex: 1,
  },
  fg1: {
    flexGrow: 1,
  },
  row: {flexDirection: 'row'},
  rowBetween: {flexDirection: 'row', justifyContent: 'space-between'},
  col: {flexDirection: 'column'},
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  capitalize: {textTransform: 'capitalize'},
  contain: {resizeMode: 'contain'},
  avoidNotch: {
    marginTop: Platform.OS === 'android' ? StatusBar.currentHeight : null,
  },
  aic: {alignItems: 'center'},
  ais: {alignItems: 'flex-start'},
  aie: {alignItems: 'flex-end'},
  asc: {alignSelf: 'center'},
  ass: {alignSelf: 'flex-start'},
  ase: {alignSelf: 'flex-end'},
  jcc: {justifyContent: 'center'},
  jcsa: {justifyContent: 'space-around'},
  jcse: {justifyContent: 'space-evenly'},
  jcsb: {justifyContent: 'space-between'},
  jcfs: {justifyContent: 'flex-start'},
  jcfe: {justifyContent: 'flex-end'},
  tac: {textAlign: 'center'},
  ofh: {overflow: 'hidden'},
  bgLightYellow: {backgroundColor: '#fff9e5'},
  bgYellow: {backgroundColor: Colors.yellow},
  textYellow: {color: Colors.yellow},
  bgWhite: {backgroundColor: Colors.white},
  bgred: {backgroundColor: 'red'},
  bgTheme: {backgroundColor: Colors.pink},
  textLight: {color: '#575757'},
  dividerH: {borderBottomWidth: 1, borderBottomColor: Colors.bordercolor},
  imgFull: {width: '100%', height: '100%', resizeMode: 'contain'},
  textMute: {
    color: '#B1B1B1',
  },
  textTheme: {
    color: Colors.pink,
  },
  bgGray: {
    backgroundColor: Colors.bgGray,
  },
  bct: {
    borderColor: 'transparent',
  },
  placeholderDark: {
    color: Colors.placeholderDark,
  },
  dividerV: {
    borderRightWidth: 0.6,
    borderRightColor: Colors.placeholder,
    height: '100%',
  },
  panel: {
    backgroundColor: Colors.white,
    flex: 1,
  },
  centerPanel: {
    width: width - normalize(16),
    alignSelf: 'center',
  },
  bgInput: {
    backgroundColor: '#f2f2f2',
  },
  imgResponsive: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e9f2',
    width: '100%',
    marginVertical: normalize(16),
  },
  //    Spacing

  //Margin
  m0: {margin: 0},
  m1: {margin: normalize(1)},
  m2: {margin: normalize(2)},
  m3: {margin: normalize(3)},
  m4: {margin: normalize(4)},
  m5: {margin: normalize(5)},
  m6: {margin: normalize(6)},
  m7: {margin: normalize(7)},
  m8: {margin: normalize(8)},
  m9: {margin: normalize(9)},
  m10: {margin: normalize(10)},
  m11: {margin: normalize(11)},
  m12: {margin: normalize(12)},
  m13: {margin: normalize(13)},
  m14: {margin: normalize(14)},
  m15: {margin: normalize(15)},
  m16: {margin: normalize(16)},
  m17: {margin: normalize(17)},
  m18: {margin: normalize(18)},
  m19: {margin: normalize(19)},
  m20: {margin: normalize(20)},
  m21: {margin: normalize(21)},
  m22: {margin: normalize(22)},
  m23: {margin: normalize(23)},
  m24: {margin: normalize(24)},
  m25: {margin: normalize(25)},
  m26: {margin: normalize(26)},
  m27: {margin: normalize(27)},
  m28: {margin: normalize(28)},
  m29: {margin: normalize(29)},
  m30: {margin: normalize(30)},
  m31: {margin: normalize(31)},
  m32: {margin: normalize(32)},
  m33: {margin: normalize(33)},
  m34: {margin: normalize(34)},
  m35: {margin: normalize(35)},
  m36: {margin: normalize(36)},
  m37: {margin: normalize(37)},
  m38: {margin: normalize(38)},
  m39: {margin: normalize(39)},
  m40: {margin: normalize(40)},
  m41: {margin: normalize(41)},
  m42: {margin: normalize(42)},
  m43: {margin: normalize(43)},
  m44: {margin: normalize(44)},
  m45: {margin: normalize(45)},
  m46: {margin: normalize(46)},
  m47: {margin: normalize(47)},
  m48: {margin: normalize(48)},
  m49: {margin: normalize(49)},
  m50: {margin: normalize(50)},
  ml0: {marginLeft: 0},
  ml1: {marginLeft: normalize(1)},
  ml2: {marginLeft: normalize(2)},
  ml3: {marginLeft: normalize(3)},
  ml4: {marginLeft: normalize(4)},
  ml5: {marginLeft: normalize(5)},
  ml6: {marginLeft: normalize(6)},
  ml7: {marginLeft: normalize(7)},
  ml8: {marginLeft: normalize(8)},
  ml9: {marginLeft: normalize(9)},
  ml10: {marginLeft: normalize(10)},
  ml11: {marginLeft: normalize(11)},
  ml12: {marginLeft: normalize(12)},
  ml13: {marginLeft: normalize(13)},
  ml14: {marginLeft: normalize(14)},
  ml15: {marginLeft: normalize(15)},
  ml16: {marginLeft: normalize(16)},
  ml17: {marginLeft: normalize(17)},
  ml18: {marginLeft: normalize(18)},
  ml19: {marginLeft: normalize(19)},
  ml20: {marginLeft: normalize(20)},
  ml21: {marginLeft: normalize(21)},
  ml22: {marginLeft: normalize(22)},
  ml23: {marginLeft: normalize(23)},
  ml24: {marginLeft: normalize(24)},
  ml25: {marginLeft: normalize(25)},
  ml26: {marginLeft: normalize(26)},
  ml27: {marginLeft: normalize(27)},
  ml28: {marginLeft: normalize(28)},
  ml29: {marginLeft: normalize(29)},
  ml30: {marginLeft: normalize(30)},
  ml31: {marginLeft: normalize(31)},
  ml32: {marginLeft: normalize(32)},
  ml33: {marginLeft: normalize(33)},
  ml34: {marginLeft: normalize(34)},
  ml35: {marginLeft: normalize(35)},
  ml36: {marginLeft: normalize(36)},
  ml37: {marginLeft: normalize(37)},
  ml38: {marginLeft: normalize(38)},
  ml39: {marginLeft: normalize(39)},
  ml40: {marginLeft: normalize(40)},
  ml41: {marginLeft: normalize(41)},
  ml42: {marginLeft: normalize(42)},
  ml43: {marginLeft: normalize(43)},
  ml44: {marginLeft: normalize(44)},
  ml45: {marginLeft: normalize(45)},
  ml46: {marginLeft: normalize(46)},
  ml47: {marginLeft: normalize(47)},
  ml48: {marginLeft: normalize(48)},
  ml49: {marginLeft: normalize(49)},
  ml50: {marginLeft: normalize(50)},

  mr0: {marginRight: 0},
  mr1: {marginRight: normalize(1)},
  mr2: {marginRight: normalize(2)},
  mr3: {marginRight: normalize(3)},
  mr4: {marginRight: normalize(4)},
  mr5: {marginRight: normalize(5)},
  mr6: {marginRight: normalize(6)},
  mr7: {marginRight: normalize(7)},
  mr8: {marginRight: normalize(8)},
  mr9: {marginRight: normalize(9)},
  mr10: {marginRight: normalize(10)},
  mr11: {marginRight: normalize(11)},
  mr12: {marginRight: normalize(12)},
  mr13: {marginRight: normalize(13)},
  mr14: {marginRight: normalize(14)},
  mr15: {marginRight: normalize(15)},
  mr16: {marginRight: normalize(16)},
  mr17: {marginRight: normalize(17)},
  mr18: {marginRight: normalize(18)},
  mr19: {marginRight: normalize(19)},
  mr20: {marginRight: normalize(20)},
  mr21: {marginRight: normalize(21)},
  mr22: {marginRight: normalize(22)},
  mr23: {marginRight: normalize(23)},
  mr24: {marginRight: normalize(24)},
  mr25: {marginRight: normalize(25)},
  mr26: {marginRight: normalize(26)},
  mr27: {marginRight: normalize(27)},
  mr28: {marginRight: normalize(28)},
  mr29: {marginRight: normalize(29)},
  mr30: {marginRight: normalize(30)},
  mr31: {marginRight: normalize(31)},
  mr32: {marginRight: normalize(32)},
  mr33: {marginRight: normalize(33)},
  mr34: {marginRight: normalize(34)},
  mr35: {marginRight: normalize(35)},
  mr36: {marginRight: normalize(36)},
  mr37: {marginRight: normalize(37)},
  mr38: {marginRight: normalize(38)},
  mr39: {marginRight: normalize(39)},
  mr40: {marginRight: normalize(40)},
  mr41: {marginRight: normalize(41)},
  mr42: {marginRight: normalize(42)},
  mr43: {marginRight: normalize(43)},
  mr44: {marginRight: normalize(44)},
  mr45: {marginRight: normalize(45)},
  mr46: {marginRight: normalize(46)},
  mr47: {marginRight: normalize(47)},
  mr48: {marginRight: normalize(48)},
  mr49: {marginRight: normalize(49)},
  mr50: {marginRight: normalize(50)},

  mt0: {marginTop: 0},
  mt1: {marginTop: normalize(1)},
  mt2: {marginTop: normalize(2)},
  mt3: {marginTop: normalize(3)},
  mt4: {marginTop: normalize(4)},
  mt5: {marginTop: normalize(5)},
  mt6: {marginTop: normalize(6)},
  mt7: {marginTop: normalize(7)},
  mt8: {marginTop: normalize(8)},
  mt9: {marginTop: normalize(9)},
  mt10: {marginTop: normalize(10)},
  mt11: {marginTop: normalize(11)},
  mt12: {marginTop: normalize(12)},
  mt13: {marginTop: normalize(13)},
  mt14: {marginTop: normalize(14)},
  mt15: {marginTop: normalize(15)},
  mt16: {marginTop: normalize(16)},
  mt17: {marginTop: normalize(17)},
  mt18: {marginTop: normalize(18)},
  mt19: {marginTop: normalize(19)},
  mt20: {marginTop: normalize(20)},
  mt21: {marginTop: normalize(21)},
  mt22: {marginTop: normalize(22)},
  mt23: {marginTop: normalize(23)},
  mt24: {marginTop: normalize(24)},
  mt25: {marginTop: normalize(25)},
  mt26: {marginTop: normalize(26)},
  mt27: {marginTop: normalize(27)},
  mt28: {marginTop: normalize(28)},
  mt29: {marginTop: normalize(29)},
  mt30: {marginTop: normalize(30)},
  mt31: {marginTop: normalize(31)},
  mt32: {marginTop: normalize(32)},
  mt33: {marginTop: normalize(33)},
  mt34: {marginTop: normalize(34)},
  mt35: {marginTop: normalize(35)},
  mt36: {marginTop: normalize(36)},
  mt37: {marginTop: normalize(37)},
  mt38: {marginTop: normalize(38)},
  mt39: {marginTop: normalize(39)},
  mt40: {marginTop: normalize(40)},
  mt41: {marginTop: normalize(41)},
  mt42: {marginTop: normalize(42)},
  mt43: {marginTop: normalize(43)},
  mt44: {marginTop: normalize(44)},
  mt45: {marginTop: normalize(45)},
  mt46: {marginTop: normalize(46)},
  mt47: {marginTop: normalize(47)},
  mt48: {marginTop: normalize(48)},
  mt49: {marginTop: normalize(49)},
  mt50: {marginTop: normalize(50)},

  mb0: {marginBottom: 0},
  mb1: {marginBottom: normalize(1)},
  mb2: {marginBottom: normalize(2)},
  mb3: {marginBottom: normalize(3)},
  mb4: {marginBottom: normalize(4)},
  mb5: {marginBottom: normalize(5)},
  mb6: {marginBottom: normalize(6)},
  mb7: {marginBottom: normalize(7)},
  mb8: {marginBottom: normalize(8)},
  mb9: {marginBottom: normalize(9)},
  mb10: {marginBottom: normalize(10)},
  mb11: {marginBottom: normalize(11)},
  mb12: {marginBottom: normalize(12)},
  mb13: {marginBottom: normalize(13)},
  mb14: {marginBottom: normalize(14)},
  mb15: {marginBottom: normalize(15)},
  mb16: {marginBottom: normalize(16)},
  mb17: {marginBottom: normalize(17)},
  mb18: {marginBottom: normalize(18)},
  mb19: {marginBottom: normalize(19)},
  mb20: {marginBottom: normalize(20)},
  mb21: {marginBottom: normalize(21)},
  mb22: {marginBottom: normalize(22)},
  mb23: {marginBottom: normalize(23)},
  mb24: {marginBottom: normalize(24)},
  mb25: {marginBottom: normalize(25)},
  mb26: {marginBottom: normalize(26)},
  mb27: {marginBottom: normalize(27)},
  mb28: {marginBottom: normalize(28)},
  mb29: {marginBottom: normalize(29)},
  mb30: {marginBottom: normalize(30)},
  mb31: {marginBottom: normalize(31)},
  mb32: {marginBottom: normalize(32)},
  mb33: {marginBottom: normalize(33)},
  mb34: {marginBottom: normalize(34)},
  mb35: {marginBottom: normalize(35)},
  mb36: {marginBottom: normalize(36)},
  mb37: {marginBottom: normalize(37)},
  mb38: {marginBottom: normalize(38)},
  mb39: {marginBottom: normalize(39)},
  mb40: {marginBottom: normalize(40)},
  mb41: {marginBottom: normalize(41)},
  mb42: {marginBottom: normalize(42)},
  mb43: {marginBottom: normalize(43)},
  mb44: {marginBottom: normalize(44)},
  mb45: {marginBottom: normalize(45)},
  mb46: {marginBottom: normalize(46)},
  mb47: {marginBottom: normalize(47)},
  mb48: {marginBottom: normalize(48)},
  mb49: {marginBottom: normalize(49)},
  mb50: {marginBottom: normalize(50)},
  mb_keyboard: {marginBottom: normalize(150)},

  mx0: {marginHorizontal: 0},
  mx1: {marginHorizontal: normalize(1)},
  mx2: {marginHorizontal: normalize(2)},
  mx3: {marginHorizontal: normalize(3)},
  mx4: {marginHorizontal: normalize(4)},
  mx5: {marginHorizontal: normalize(5)},
  mx6: {marginHorizontal: normalize(6)},
  mx7: {marginHorizontal: normalize(7)},
  mx8: {marginHorizontal: normalize(8)},
  mx9: {marginHorizontal: normalize(9)},
  mx10: {marginHorizontal: normalize(10)},
  mx11: {marginHorizontal: normalize(11)},
  mx12: {marginHorizontal: normalize(12)},
  mx13: {marginHorizontal: normalize(13)},
  mx14: {marginHorizontal: normalize(14)},
  mx15: {marginHorizontal: normalize(15)},
  mx16: {marginHorizontal: normalize(16)},
  mx17: {marginHorizontal: normalize(17)},
  mx18: {marginHorizontal: normalize(18)},
  mx19: {marginHorizontal: normalize(19)},
  mx20: {marginHorizontal: normalize(20)},
  mx21: {marginHorizontal: normalize(21)},
  mx22: {marginHorizontal: normalize(22)},
  mx23: {marginHorizontal: normalize(23)},
  mx24: {marginHorizontal: normalize(24)},
  mx25: {marginHorizontal: normalize(25)},
  mx26: {marginHorizontal: normalize(26)},
  mx27: {marginHorizontal: normalize(27)},
  mx28: {marginHorizontal: normalize(28)},
  mx29: {marginHorizontal: normalize(29)},
  mx30: {marginHorizontal: normalize(30)},
  mx31: {marginHorizontal: normalize(31)},
  mx32: {marginHorizontal: normalize(32)},
  mx33: {marginHorizontal: normalize(33)},
  mx34: {marginHorizontal: normalize(34)},
  mx35: {marginHorizontal: normalize(35)},
  mx36: {marginHorizontal: normalize(36)},
  mx37: {marginHorizontal: normalize(37)},
  mx38: {marginHorizontal: normalize(38)},
  mx39: {marginHorizontal: normalize(39)},
  mx40: {marginHorizontal: normalize(40)},
  mx41: {marginHorizontal: normalize(41)},
  mx42: {marginHorizontal: normalize(42)},
  mx43: {marginHorizontal: normalize(43)},
  mx44: {marginHorizontal: normalize(44)},
  mx45: {marginHorizontal: normalize(45)},
  mx46: {marginHorizontal: normalize(46)},
  mx47: {marginHorizontal: normalize(47)},
  mx48: {marginHorizontal: normalize(48)},
  mx49: {marginHorizontal: normalize(49)},
  mx50: {marginHorizontal: normalize(50)},

  my0: {marginVertical: 0},
  my1: {marginVertical: normalize(1)},
  my2: {marginVertical: normalize(2)},
  my3: {marginVertical: normalize(3)},
  my4: {marginVertical: normalize(4)},
  my5: {marginVertical: normalize(5)},
  my6: {marginVertical: normalize(6)},
  my7: {marginVertical: normalize(7)},
  my8: {marginVertical: normalize(8)},
  my9: {marginVertical: normalize(9)},
  my10: {marginVertical: normalize(10)},
  my11: {marginVertical: normalize(11)},
  my12: {marginVertical: normalize(12)},
  my13: {marginVertical: normalize(13)},
  my14: {marginVertical: normalize(14)},
  my15: {marginVertical: normalize(15)},
  my16: {marginVertical: normalize(16)},
  my17: {marginVertical: normalize(17)},
  my18: {marginVertical: normalize(18)},
  my19: {marginVertical: normalize(19)},
  my20: {marginVertical: normalize(20)},
  my21: {marginVertical: normalize(21)},
  my22: {marginVertical: normalize(22)},
  my23: {marginVertical: normalize(23)},
  my24: {marginVertical: normalize(24)},
  my25: {marginVertical: normalize(25)},
  my26: {marginVertical: normalize(26)},
  my27: {marginVertical: normalize(27)},
  my28: {marginVertical: normalize(28)},
  my29: {marginVertical: normalize(29)},
  my30: {marginVertical: normalize(30)},
  my31: {marginVertical: normalize(31)},
  my32: {marginVertical: normalize(32)},
  my33: {marginVertical: normalize(33)},
  my34: {marginVertical: normalize(34)},
  my35: {marginVertical: normalize(35)},
  my36: {marginVertical: normalize(36)},
  my37: {marginVertical: normalize(37)},
  my38: {marginVertical: normalize(38)},
  my39: {marginVertical: normalize(39)},
  my40: {marginVertical: normalize(40)},
  my41: {marginVertical: normalize(41)},
  my42: {marginVertical: normalize(42)},
  my43: {marginVertical: normalize(43)},
  my44: {marginVertical: normalize(44)},
  my45: {marginVertical: normalize(45)},
  my46: {marginVertical: normalize(46)},
  my47: {marginVertical: normalize(47)},
  my48: {marginVertical: normalize(48)},
  my49: {marginVertical: normalize(49)},
  my50: {marginVertical: normalize(50)},

  // Padding
  p0: {padding: 0},
  p1: {padding: normalize(1)},
  p2: {padding: normalize(2)},
  p3: {padding: normalize(3)},
  p4: {padding: normalize(4)},
  p5: {padding: normalize(5)},
  p6: {padding: normalize(6)},
  p7: {padding: normalize(7)},
  p8: {padding: normalize(8)},
  p9: {padding: normalize(9)},
  p10: {padding: normalize(10)},
  p11: {padding: normalize(11)},
  p12: {padding: normalize(12)},
  p13: {padding: normalize(13)},
  p14: {padding: normalize(14)},
  p15: {padding: normalize(15)},
  p16: {padding: normalize(16)},
  p17: {padding: normalize(17)},
  p18: {padding: normalize(18)},
  p19: {padding: normalize(19)},
  p20: {padding: normalize(20)},
  p21: {padding: normalize(21)},
  p22: {padding: normalize(22)},
  p23: {padding: normalize(23)},
  p24: {padding: normalize(24)},
  p25: {padding: normalize(25)},
  p26: {padding: normalize(26)},
  p27: {padding: normalize(27)},
  p28: {padding: normalize(28)},
  p29: {padding: normalize(29)},
  p30: {padding: normalize(30)},
  p31: {padding: normalize(31)},
  p32: {padding: normalize(32)},
  p33: {padding: normalize(33)},
  p34: {padding: normalize(34)},
  p35: {padding: normalize(35)},
  p36: {padding: normalize(36)},
  p37: {padding: normalize(37)},
  p38: {padding: normalize(38)},
  p39: {padding: normalize(39)},
  p40: {padding: normalize(40)},
  p41: {padding: normalize(41)},
  p42: {padding: normalize(42)},
  p43: {padding: normalize(43)},
  p44: {padding: normalize(44)},
  p45: {padding: normalize(45)},
  p46: {padding: normalize(46)},
  p47: {padding: normalize(47)},
  p48: {padding: normalize(48)},
  p49: {padding: normalize(49)},
  p50: {padding: normalize(50)},
  pl0: {paddingLeft: 0},
  pl1: {paddingLeft: normalize(1)},
  pl2: {paddingLeft: normalize(2)},
  pl3: {paddingLeft: normalize(3)},
  pl4: {paddingLeft: normalize(4)},
  pl5: {paddingLeft: normalize(5)},
  pl6: {paddingLeft: normalize(6)},
  pl7: {paddingLeft: normalize(7)},
  pl8: {paddingLeft: normalize(8)},
  pl9: {paddingLeft: normalize(9)},
  pl10: {paddingLeft: normalize(10)},
  pl11: {paddingLeft: normalize(11)},
  pl12: {paddingLeft: normalize(12)},
  pl13: {paddingLeft: normalize(13)},
  pl14: {paddingLeft: normalize(14)},
  pl15: {paddingLeft: normalize(15)},
  pl16: {paddingLeft: normalize(16)},
  pl17: {paddingLeft: normalize(17)},
  pl18: {paddingLeft: normalize(18)},
  pl19: {paddingLeft: normalize(19)},
  pl20: {paddingLeft: normalize(20)},
  pl21: {paddingLeft: normalize(21)},
  pl22: {paddingLeft: normalize(22)},
  pl23: {paddingLeft: normalize(23)},
  pl24: {paddingLeft: normalize(24)},
  pl25: {paddingLeft: normalize(25)},
  pl26: {paddingLeft: normalize(26)},
  pl27: {paddingLeft: normalize(27)},
  pl28: {paddingLeft: normalize(28)},
  pl29: {paddingLeft: normalize(29)},
  pl30: {paddingLeft: normalize(30)},
  pl31: {paddingLeft: normalize(31)},
  pl32: {paddingLeft: normalize(32)},
  pl33: {paddingLeft: normalize(33)},
  pl34: {paddingLeft: normalize(34)},
  pl35: {paddingLeft: normalize(35)},
  pl36: {paddingLeft: normalize(36)},
  pl37: {paddingLeft: normalize(37)},
  pl38: {paddingLeft: normalize(38)},
  pl39: {paddingLeft: normalize(39)},
  pl40: {paddingLeft: normalize(40)},
  pl41: {paddingLeft: normalize(41)},
  pl42: {paddingLeft: normalize(42)},
  pl43: {paddingLeft: normalize(43)},
  pl44: {paddingLeft: normalize(44)},
  pl45: {paddingLeft: normalize(45)},
  pl46: {paddingLeft: normalize(46)},
  pl47: {paddingLeft: normalize(47)},
  pl48: {paddingLeft: normalize(48)},
  pl49: {paddingLeft: normalize(49)},
  pl50: {paddingLeft: normalize(50)},

  pr0: {paddingRight: 0},
  pr1: {paddingRight: normalize(1)},
  pr2: {paddingRight: normalize(2)},
  pr3: {paddingRight: normalize(3)},
  pr4: {paddingRight: normalize(4)},
  pr5: {paddingRight: normalize(5)},
  pr6: {paddingRight: normalize(6)},
  pr7: {paddingRight: normalize(7)},
  pr8: {paddingRight: normalize(8)},
  pr9: {paddingRight: normalize(9)},
  pr10: {paddingRight: normalize(10)},
  pr11: {paddingRight: normalize(11)},
  pr12: {paddingRight: normalize(12)},
  pr13: {paddingRight: normalize(13)},
  pr14: {paddingRight: normalize(14)},
  pr15: {paddingRight: normalize(15)},
  pr16: {paddingRight: normalize(16)},
  pr17: {paddingRight: normalize(17)},
  pr18: {paddingRight: normalize(18)},
  pr19: {paddingRight: normalize(19)},
  pr20: {paddingRight: normalize(20)},
  pr21: {paddingRight: normalize(21)},
  pr22: {paddingRight: normalize(22)},
  pr23: {paddingRight: normalize(23)},
  pr24: {paddingRight: normalize(24)},
  pr25: {paddingRight: normalize(25)},
  pr26: {paddingRight: normalize(26)},
  pr27: {paddingRight: normalize(27)},
  pr28: {paddingRight: normalize(28)},
  pr29: {paddingRight: normalize(29)},
  pr30: {paddingRight: normalize(30)},
  pr31: {paddingRight: normalize(31)},
  pr32: {paddingRight: normalize(32)},
  pr33: {paddingRight: normalize(33)},
  pr34: {paddingRight: normalize(34)},
  pr35: {paddingRight: normalize(35)},
  pr36: {paddingRight: normalize(36)},
  pr37: {paddingRight: normalize(37)},
  pr38: {paddingRight: normalize(38)},
  pr39: {paddingRight: normalize(39)},
  pr40: {paddingRight: normalize(40)},
  pr41: {paddingRight: normalize(41)},
  pr42: {paddingRight: normalize(42)},
  pr43: {paddingRight: normalize(43)},
  pr44: {paddingRight: normalize(44)},
  pr45: {paddingRight: normalize(45)},
  pr46: {paddingRight: normalize(46)},
  pr47: {paddingRight: normalize(47)},
  pr48: {paddingRight: normalize(48)},
  pr49: {paddingRight: normalize(49)},
  pr50: {paddingRight: normalize(50)},

  pt0: {paddingTop: 0},
  pt1: {paddingTop: normalize(1)},
  pt2: {paddingTop: normalize(2)},
  pt3: {paddingTop: normalize(3)},
  pt4: {paddingTop: normalize(4)},
  pt5: {paddingTop: normalize(5)},
  pt6: {paddingTop: normalize(6)},
  pt7: {paddingTop: normalize(7)},
  pt8: {paddingTop: normalize(8)},
  pt9: {paddingTop: normalize(9)},
  pt10: {paddingTop: normalize(10)},
  pt11: {paddingTop: normalize(11)},
  pt12: {paddingTop: normalize(12)},
  pt13: {paddingTop: normalize(13)},
  pt14: {paddingTop: normalize(14)},
  pt15: {paddingTop: normalize(15)},
  pt16: {paddingTop: normalize(16)},
  pt17: {paddingTop: normalize(17)},
  pt18: {paddingTop: normalize(18)},
  pt19: {paddingTop: normalize(19)},
  pt20: {paddingTop: normalize(20)},
  pt21: {paddingTop: normalize(21)},
  pt22: {paddingTop: normalize(22)},
  pt23: {paddingTop: normalize(23)},
  pt24: {paddingTop: normalize(24)},
  pt25: {paddingTop: normalize(25)},
  pt26: {paddingTop: normalize(26)},
  pt27: {paddingTop: normalize(27)},
  pt28: {paddingTop: normalize(28)},
  pt29: {paddingTop: normalize(29)},
  pt30: {paddingTop: normalize(30)},
  pt31: {paddingTop: normalize(31)},
  pt32: {paddingTop: normalize(32)},
  pt33: {paddingTop: normalize(33)},
  pt34: {paddingTop: normalize(34)},
  pt35: {paddingTop: normalize(35)},
  pt36: {paddingTop: normalize(36)},
  pt37: {paddingTop: normalize(37)},
  pt38: {paddingTop: normalize(38)},
  pt39: {paddingTop: normalize(39)},
  pt40: {paddingTop: normalize(40)},
  pt41: {paddingTop: normalize(41)},
  pt42: {paddingTop: normalize(42)},
  pt43: {paddingTop: normalize(43)},
  pt44: {paddingTop: normalize(44)},
  pt45: {paddingTop: normalize(45)},
  pt46: {paddingTop: normalize(46)},
  pt47: {paddingTop: normalize(47)},
  pt48: {paddingTop: normalize(48)},
  pt49: {paddingTop: normalize(49)},
  pt50: {paddingTop: normalize(50)},

  pb0: {paddingBottom: 0},
  pb1: {paddingBottom: normalize(1)},
  pb2: {paddingBottom: normalize(2)},
  pb3: {paddingBottom: normalize(3)},
  pb4: {paddingBottom: normalize(4)},
  pb5: {paddingBottom: normalize(5)},
  pb6: {paddingBottom: normalize(6)},
  pb7: {paddingBottom: normalize(7)},
  pb8: {paddingBottom: normalize(8)},
  pb9: {paddingBottom: normalize(9)},
  pb10: {paddingBottom: normalize(10)},
  pb11: {paddingBottom: normalize(11)},
  pb12: {paddingBottom: normalize(12)},
  pb13: {paddingBottom: normalize(13)},
  pb14: {paddingBottom: normalize(14)},
  pb15: {paddingBottom: normalize(15)},
  pb16: {paddingBottom: normalize(16)},
  pb17: {paddingBottom: normalize(17)},
  pb18: {paddingBottom: normalize(18)},
  pb19: {paddingBottom: normalize(19)},
  pb20: {paddingBottom: normalize(20)},
  pb21: {paddingBottom: normalize(21)},
  pb22: {paddingBottom: normalize(22)},
  pb23: {paddingBottom: normalize(23)},
  pb24: {paddingBottom: normalize(24)},
  pb25: {paddingBottom: normalize(25)},
  pb26: {paddingBottom: normalize(26)},
  pb27: {paddingBottom: normalize(27)},
  pb28: {paddingBottom: normalize(28)},
  pb29: {paddingBottom: normalize(29)},
  pb30: {paddingBottom: normalize(30)},
  pb31: {paddingBottom: normalize(31)},
  pb32: {paddingBottom: normalize(32)},
  pb33: {paddingBottom: normalize(33)},
  pb34: {paddingBottom: normalize(34)},
  pb35: {paddingBottom: normalize(35)},
  pb36: {paddingBottom: normalize(36)},
  pb37: {paddingBottom: normalize(37)},
  pb38: {paddingBottom: normalize(38)},
  pb39: {paddingBottom: normalize(39)},
  pb40: {paddingBottom: normalize(40)},
  pb41: {paddingBottom: normalize(41)},
  pb42: {paddingBottom: normalize(42)},
  pb43: {paddingBottom: normalize(43)},
  pb44: {paddingBottom: normalize(44)},
  pb45: {paddingBottom: normalize(45)},
  pb46: {paddingBottom: normalize(46)},
  pb47: {paddingBottom: normalize(47)},
  pb48: {paddingBottom: normalize(48)},
  pb49: {paddingBottom: normalize(49)},
  pb50: {paddingBottom: normalize(50)},

  px0: {paddingHorizontal: 0},
  px1: {paddingHorizontal: normalize(1)},
  px2: {paddingHorizontal: normalize(2)},
  px3: {paddingHorizontal: normalize(3)},
  px4: {paddingHorizontal: normalize(4)},
  px5: {paddingHorizontal: normalize(5)},
  px6: {paddingHorizontal: normalize(6)},
  px7: {paddingHorizontal: normalize(7)},
  px8: {paddingHorizontal: normalize(8)},
  px9: {paddingHorizontal: normalize(9)},
  px10: {paddingHorizontal: normalize(10)},
  px11: {paddingHorizontal: normalize(11)},
  px12: {paddingHorizontal: normalize(12)},
  px13: {paddingHorizontal: normalize(13)},
  px14: {paddingHorizontal: normalize(14)},
  px15: {paddingHorizontal: normalize(15)},
  px16: {paddingHorizontal: normalize(16)},
  px17: {paddingHorizontal: normalize(17)},
  px18: {paddingHorizontal: normalize(18)},
  px19: {paddingHorizontal: normalize(19)},
  px20: {paddingHorizontal: normalize(20)},
  px21: {paddingHorizontal: normalize(21)},
  px22: {paddingHorizontal: normalize(22)},
  px23: {paddingHorizontal: normalize(23)},
  px24: {paddingHorizontal: normalize(24)},
  px25: {paddingHorizontal: normalize(25)},
  px26: {paddingHorizontal: normalize(26)},
  px27: {paddingHorizontal: normalize(27)},
  px28: {paddingHorizontal: normalize(28)},
  px29: {paddingHorizontal: normalize(29)},
  px30: {paddingHorizontal: normalize(30)},
  px31: {paddingHorizontal: normalize(31)},
  px32: {paddingHorizontal: normalize(32)},
  px33: {paddingHorizontal: normalize(33)},
  px34: {paddingHorizontal: normalize(34)},
  px35: {paddingHorizontal: normalize(35)},
  px36: {paddingHorizontal: normalize(36)},
  px37: {paddingHorizontal: normalize(37)},
  px38: {paddingHorizontal: normalize(38)},
  px39: {paddingHorizontal: normalize(39)},
  px40: {paddingHorizontal: normalize(40)},
  px41: {paddingHorizontal: normalize(41)},
  px42: {paddingHorizontal: normalize(42)},
  px43: {paddingHorizontal: normalize(43)},
  px44: {paddingHorizontal: normalize(44)},
  px45: {paddingHorizontal: normalize(45)},
  px46: {paddingHorizontal: normalize(46)},
  px47: {paddingHorizontal: normalize(47)},
  px48: {paddingHorizontal: normalize(48)},
  px49: {paddingHorizontal: normalize(49)},
  px50: {paddingHorizontal: normalize(50)},

  py0: {paddingVertical: 0},
  py1: {paddingVertical: normalize(1)},
  py2: {paddingVertical: normalize(2)},
  py3: {paddingVertical: normalize(3)},
  py4: {paddingVertical: normalize(4)},
  py5: {paddingVertical: normalize(5)},
  py6: {paddingVertical: normalize(6)},
  py7: {paddingVertical: normalize(7)},
  py8: {paddingVertical: normalize(8)},
  py9: {paddingVertical: normalize(9)},
  py10: {paddingVertical: normalize(10)},
  py11: {paddingVertical: normalize(11)},
  py12: {paddingVertical: normalize(12)},
  py13: {paddingVertical: normalize(13)},
  py14: {paddingVertical: normalize(14)},
  py15: {paddingVertical: normalize(15)},
  py16: {paddingVertical: normalize(16)},
  py17: {paddingVertical: normalize(17)},
  py18: {paddingVertical: normalize(18)},
  py19: {paddingVertical: normalize(19)},
  py20: {paddingVertical: normalize(20)},
  py21: {paddingVertical: normalize(21)},
  py22: {paddingVertical: normalize(22)},
  py23: {paddingVertical: normalize(23)},
  py24: {paddingVertical: normalize(24)},
  py25: {paddingVertical: normalize(25)},
  py26: {paddingVertical: normalize(26)},
  py27: {paddingVertical: normalize(27)},
  py28: {paddingVertical: normalize(28)},
  py29: {paddingVertical: normalize(29)},
  py30: {paddingVertical: normalize(30)},
  py31: {paddingVertical: normalize(31)},
  py32: {paddingVertical: normalize(32)},
  py33: {paddingVertical: normalize(33)},
  py34: {paddingVertical: normalize(34)},
  py35: {paddingVertical: normalize(35)},
  py36: {paddingVertical: normalize(36)},
  py37: {paddingVertical: normalize(37)},
  py38: {paddingVertical: normalize(38)},
  py39: {paddingVertical: normalize(39)},
  py40: {paddingVertical: normalize(40)},
  py41: {paddingVertical: normalize(41)},
  py42: {paddingVertical: normalize(42)},
  py43: {paddingVertical: normalize(43)},
  py44: {paddingVertical: normalize(44)},
  py45: {paddingVertical: normalize(45)},
  py46: {paddingVertical: normalize(46)},
  py47: {paddingVertical: normalize(47)},
  py48: {paddingVertical: normalize(48)},
  py49: {paddingVertical: normalize(49)},
  py50: {paddingVertical: normalize(50)},

  br5: {borderRadius: normalize(5), overflow: 'hidden'},
  br6: {borderRadius: normalize(6), overflow: 'hidden'},
  br7: {borderRadius: normalize(7), overflow: 'hidden'},
  br8: {borderRadius: normalize(8), overflow: 'hidden'},
  br9: {borderRadius: normalize(9), overflow: 'hidden'},
  br10: {borderRadius: normalize(10), overflow: 'hidden'},
  br11: {borderRadius: normalize(11), overflow: 'hidden'},
  br12: {borderRadius: normalize(12), overflow: 'hidden'},
  br13: {borderRadius: normalize(13), overflow: 'hidden'},
  br14: {borderRadius: normalize(14), overflow: 'hidden'},
  br15: {borderRadius: normalize(15), overflow: 'hidden'},
  br16: {borderRadius: normalize(16), overflow: 'hidden'},
  br17: {borderRadius: normalize(17), overflow: 'hidden'},
  br18: {borderRadius: normalize(18), overflow: 'hidden'},
  br19: {borderRadius: normalize(19), overflow: 'hidden'},
  br20: {borderRadius: normalize(20), overflow: 'hidden'},
  br21: {borderRadius: normalize(21), overflow: 'hidden'},
  br22: {borderRadius: normalize(22), overflow: 'hidden'},
  br23: {borderRadius: normalize(23), overflow: 'hidden'},
  br24: {borderRadius: normalize(24), overflow: 'hidden'},
  br25: {borderRadius: normalize(25), overflow: 'hidden'},
  br26: {borderRadius: normalize(26), overflow: 'hidden'},
  br27: {borderRadius: normalize(27), overflow: 'hidden'},
  br28: {borderRadius: normalize(28), overflow: 'hidden'},
  br29: {borderRadius: normalize(29), overflow: 'hidden'},
  br30: {borderRadius: normalize(30), overflow: 'hidden'},
  br31: {borderRadius: normalize(31), overflow: 'hidden'},
  br32: {borderRadius: normalize(32), overflow: 'hidden'},
  br33: {borderRadius: normalize(33), overflow: 'hidden'},
  br34: {borderRadius: normalize(34), overflow: 'hidden'},
  br35: {borderRadius: normalize(35), overflow: 'hidden'},
  br36: {borderRadius: normalize(36), overflow: 'hidden'},
  br37: {borderRadius: normalize(37), overflow: 'hidden'},
  br38: {borderRadius: normalize(38), overflow: 'hidden'},
  br39: {borderRadius: normalize(39), overflow: 'hidden'},
  br40: {borderRadius: normalize(40), overflow: 'hidden'},
  br41: {borderRadius: normalize(41), overflow: 'hidden'},
  br42: {borderRadius: normalize(42), overflow: 'hidden'},
  br43: {borderRadius: normalize(43), overflow: 'hidden'},
  br44: {borderRadius: normalize(44), overflow: 'hidden'},
  br45: {borderRadius: normalize(45), overflow: 'hidden'},
  br46: {borderRadius: normalize(46), overflow: 'hidden'},
  br47: {borderRadius: normalize(47), overflow: 'hidden'},
  br48: {borderRadius: normalize(48), overflow: 'hidden'},
  br49: {borderRadius: normalize(49), overflow: 'hidden'},
  br50: {borderRadius: normalize(50), overflow: 'hidden'},
  // Font Size
  fs8: {fontSize: Platform.OS === 'android' ? normalize(8) : normalize(7)},
  fs9: {fontSize: Platform.OS === 'android' ? normalize(9) : normalize(8)},
  fs10: {fontSize: Platform.OS === 'android' ? normalize(10) : normalize(9)},
  fs11: {fontSize: Platform.OS === 'android' ? normalize(11) : normalize(10)},
  fs12: {fontSize: Platform.OS === 'android' ? normalize(12) : normalize(11)},
  fs13: {fontSize: Platform.OS === 'android' ? normalize(13) : normalize(12)},
  fs14: {fontSize: Platform.OS === 'android' ? normalize(14) : normalize(13)},
  fs15: {fontSize: Platform.OS === 'android' ? normalize(15) : normalize(14)},
  fs16: {fontSize: Platform.OS === 'android' ? normalize(16) : normalize(15)},
  fs17: {fontSize: Platform.OS === 'android' ? normalize(17) : normalize(16)},
  fs18: {fontSize: Platform.OS === 'android' ? normalize(18) : normalize(17)},
  fs19: {fontSize: Platform.OS === 'android' ? normalize(19) : normalize(18)},
  fs20: {fontSize: Platform.OS === 'android' ? normalize(20) : normalize(19)},
  fs21: {fontSize: Platform.OS === 'android' ? normalize(21) : normalize(20)},
  fs22: {fontSize: Platform.OS === 'android' ? normalize(22) : normalize(21)},
  fs23: {fontSize: Platform.OS === 'android' ? normalize(23) : normalize(22)},
  fs24: {fontSize: Platform.OS === 'android' ? normalize(24) : normalize(23)},
  fs25: {fontSize: Platform.OS === 'android' ? normalize(25) : normalize(24)},
  fs26: {fontSize: Platform.OS === 'android' ? normalize(26) : normalize(25)},
  fs27: {fontSize: Platform.OS === 'android' ? normalize(27) : normalize(26)},
  fs28: {fontSize: Platform.OS === 'android' ? normalize(28) : normalize(27)},
  fs29: {fontSize: Platform.OS === 'android' ? normalize(29) : normalize(28)},
  fs30: {fontSize: Platform.OS === 'android' ? normalize(30) : normalize(29)},

  // Font Family
  roboto_Bold: {
    fontFamily: Fonts.Roboto_Bold,
  },
  roboto_Light: {
    fontFamily: Fonts.Roboto_Light,
  },
  roboto_Medium: {
    fontFamily: Fonts.Roboto_Medium,
  },
  roboto_Regular: {
    fontFamily: Fonts.Roboto_Regular,
  },
  roboto_Thin: {
    fontFamily: Fonts.Roboto_Thin,
  },

  // Width
  w5: {width: '5%'},
  w10: {width: '10%'},
  w15: {width: '15%'},
  w20: {width: '20%'},
  w25: {width: '25%'},
  w30: {width: '30%'},
  w35: {width: '35%'},
  w40: {width: '40%'},
  w45: {width: '45%'},
  w48: {width: '48%'},
  w50: {width: '50%'},
  w55: {width: '55%'},
  w60: {width: '60%'},
  w65: {width: '65%'},
  w70: {width: '70%'},
  w75: {width: '75%'},
  w80: {width: '80%'},
  w85: {width: '85%'},
  w90: {width: '90%'},
  w95: {width: '95%'},
  w100: {width: '100%'},

  //Height
  h100: {height: '100%'},
  h50: {height: '50%'},

  // zIndex
  z_1: {zIndex: -1},
  z0: {zIndex: 0},
  z1: {zIndex: 1},
  z2: {zIndex: 2},
  z3: {zIndex: 3},
  z4: {zIndex: 4},
  z5: {zIndex: 5},
  z6: {zIndex: 6},
  z7: {zIndex: 7},
  z8: {zIndex: 8},
  z9: {zIndex: 9},
  z10: {zIndex: 10},
  z11: {zIndex: 11},
  z12: {zIndex: 12},
  z13: {zIndex: 13},
  z14: {zIndex: 14},
  z15: {zIndex: 15},
  z16: {zIndex: 16},
  z17: {zIndex: 17},
  z18: {zIndex: 18},
  z19: {zIndex: 19},
  z20: {zIndex: 20},
  z21: {zIndex: 21},
  z22: {zIndex: 22},
  z23: {zIndex: 23},
  z24: {zIndex: 24},
  z25: {zIndex: 25},
  z26: {zIndex: 26},
  z27: {zIndex: 27},
  z28: {zIndex: 28},
  z29: {zIndex: 29},
  z30: {zIndex: 30},
  z31: {zIndex: 31},
  z32: {zIndex: 32},
  z33: {zIndex: 33},
  z34: {zIndex: 34},
  z35: {zIndex: 35},
  z36: {zIndex: 36},
  z37: {zIndex: 37},
  z38: {zIndex: 38},
  z39: {zIndex: 39},
  z40: {zIndex: 40},
  z41: {zIndex: 41},
  z42: {zIndex: 42},
  z43: {zIndex: 43},
  z44: {zIndex: 44},
  z45: {zIndex: 45},
  z46: {zIndex: 46},
  z47: {zIndex: 47},
  z48: {zIndex: 48},
  z49: {zIndex: 49},
  z50: {zIndex: 50},

  // Shadows
  shadow1: {
    shadowColor: '#BD87CE',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.16,
    shadowRadius: 1.51,
    elevation: 2,
  },
  shadow2: {
    shadowColor: '#BD87CE',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.17,
    shadowRadius: 3.05,
    elevation: 4,
  },
  shadow3: {
    shadowColor: '#BD87CE',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.19,
    shadowRadius: 5.62,
    elevation: 6,
  },
  shadow4: {
    shadowColor: '#BD87CE',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5.62,
    elevation: 8,
  },
  shadow5: {
    shadowColor: 'red',
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.21,
    shadowRadius: 7.68,
    elevation: 10,
  },
});

export default css;
